name: money_lover_clone
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  bloc: ^8.1.2
  cloud_firestore: ^4.13.6
  dev: ^1.0.0
  equatable: ^2.0.5
  firebase_auth: ^4.15.3
  firebase_core: ^2.24.2
  firebase_storage: ^11.6.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_easyloading: ^3.0.5
  flutter_screenutil: ^5.9.0
  flutter_slidable: ^3.0.1
  get_it: ^7.6.4
  google_fonts: ^6.1.0
  image_picker: ^1.0.6
  injectable: ^2.3.2
  intl: ^0.19.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  injectable_generator: ^2.4.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
