// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpWNb-_OfmXZLfCv02qJkAbrGMa5hGlVk',
    appId: '1:209080239008:web:ff837826f6343ae964dac5',
    messagingSenderId: '209080239008',
    projectId: 'aplikasi-keuangan-a604a',
    authDomain: 'aplikasi-keuangan-a604a.firebaseapp.com',
    storageBucket: 'aplikasi-keuangan-a604a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBebmID9cXNF7ePhcdlnmH6TDZzGiK10sg',
    appId: '1:209080239008:android:556f9503a1082f1464dac5',
    messagingSenderId: '209080239008',
    projectId: 'aplikasi-keuangan-a604a',
    storageBucket: 'aplikasi-keuangan-a604a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD3VAxK2ZwiNlTslG4sqeWkvpG9GoBR7lA',
    appId: '1:209080239008:ios:15d10e7838977fdb64dac5',
    messagingSenderId: '209080239008',
    projectId: 'aplikasi-keuangan-a604a',
    storageBucket: 'aplikasi-keuangan-a604a.appspot.com',
    iosClientId: '209080239008-gfggq4kv3alg1ou2n4jvl1agn0kitiq9.apps.googleusercontent.com',
    iosBundleId: 'com.example.moneyLoverClone',
  );
}
